services:
    _defaults:
        autowire: true
        autoconfigure: true

    Smsh\TicketingBridge\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/SmshTicketingBridgeBundle.php'
